changelog_dir: .changelogs
entry:
    types:
        - description: "null"
          group_title: Added
          hidden: false
          id: new_feat
          title: New Feature
        - description: "null"
          group_title: Fixed
          hidden: false
          id: bug_fix
          title: Bug Fixed
        - description: "null"
          group_title: Changed
          hidden: false
          id: feat_change
          title: Feature change
        - description: "null"
          group_title: Deprecated
          hidden: false
          id: deprecate
          title: Deprecation
        - description: "null"
          group_title: Removed
          hidden: false
          id: rem_feat
          title: Feature removal
        - description: "null"
          group_title: Security
          hidden: false
          id: security
          title: Security fix
        - description: "null"
          group_title: Other
          hidden: false
          id: other
          title: Other
output_path: "null"
preRelease:
    deletePreRelease: false
    detect: true
    foldPreReleases: false
version: "2"
