default:
 image: golang:1.13-stretch

 before_script:
   - apt-get update && apt-get install -y make
   - make depends assets 

test:
 include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
