image: golang:1.14


include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml

build:
  stage: build
  script:
  script:
  - apk add make git go
  - make depends assets
  - make build-dev
