project_name: changelog

before:
  hooks:
    - go mod tidy
builds:
- id: "default"
  binary: changelog

  goos:
    - freebsd
    - linux
    - windows
    - darwin

  goarch:
    - amd64
    - arm
    - arm64

  ldflags:
    - -X gitlab.com/l0nax/changelog-go/pkg/version.Version={{.Env.VERSION}} -X gitlab.com/l0nax/changelog-go/pkg/version.Hash={{.Commit}} -X gitlab.com/l0nax/changelog-go/pkg/version.BuildTime={{.Env.BUILD_DATE}} -X gitlab.com/l0nax/changelog-go/pkg/version.Environment={{.Env.BUILD_ENVIRONMENT}}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

signs:
- cmd: gpg2
  artifacts: all

    #nfpms:
    #- replacements:
    #    386: x86_64
    #
    #  vendor: l0nax
    #  homepage: https://gitlab.com/l0nax
    #
    #  maintainer: Francesco Emanuel Bennici <benniciemanuel78@gmail.com>
    #  description: Changelog management tool
    #  license: MIT
    #
    #  formats:
    #    - deb
    #    - rpm

    #snapcrafts:
    #- publish: true
    #
    #  summary: CLI to create and manage Changelog even on big projects
    #  description: changelog is a CLI that helps a team/ person to keep track of all changes and also helps creating (and managing) a readable CHANGELOG.md
    #
    #  grade: stable
    #  license: MIT

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  - name: changelog-go
    ids:
      - default

    caveats: "See README.md"
    license: "MIT"
    skip_upload: false

    dependencies:
      - name: git

    repository:
      owner: l0nax
      name: changelog-go
      branch: development

      token: "{{ .Env.GITLAB_TOKEN }}"

      pull_request:
        enabled: true
        draft: true

        base:
          owner: l0nax
          name: changelog-go
          branch: development
