# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogGo < Formula
  desc ""
  homepage ""
  version "1.4.1"
  license "MIT"

  depends_on "git"

  on_macos do
    if Hardware::CPU.intel?
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v1.4.1/downloads/changelog_1.4.1_darwin_amd64.tar.gz"
      sha256 "b11aba5f9b3a742e3ce948a94f6abf080b3aad6f3cd5c3c13e7c804cf7bf0f56"

      def install
        bin.install "changelog"
      end
    end
    if Hardware::CPU.arm?
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v1.4.1/downloads/changelog_1.4.1_darwin_arm64.tar.gz"
      sha256 "596b645ac0169cc3d314bc655fa7117c02dba073a39d7437b1c40a800948fde6"

      def install
        bin.install "changelog"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v1.4.1/downloads/changelog_1.4.1_linux_armv6.tar.gz"
      sha256 "b8972a1e2cf5b6f5cc64a7fa5a600f0f377140300c14807b171cb24229b5c8ae"

      def install
        bin.install "changelog"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v1.4.1/downloads/changelog_1.4.1_linux_arm64.tar.gz"
      sha256 "ed4c2c9a02bc5a8f475eb6aaeca93e566bb7c1cfee0084bacac835d5d125ecf3"

      def install
        bin.install "changelog"
      end
    end
    if Hardware::CPU.intel?
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v1.4.1/downloads/changelog_1.4.1_linux_amd64.tar.gz"
      sha256 "6a51dff9a277596065d4073338f166c565f5a168cf7288aaf78022f1299cbb3d"

      def install
        bin.install "changelog"
      end
    end
  end

  def caveats
    <<~EOS
      See README.md
    EOS
  end
end
