# This file was generated by GoReleaser. DO NOT EDIT.
cask "changelog" do
  version "2.0.1"

  on_macos do
    on_arm do
      sha256 "338e9d4b0345b22673a7de7767031b06124b517fbe3c4716f8cade6e9057b841"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aba91ad15b17b1e320032706c35b6c4f02e036a5987e9486b43a425b189e4c1d"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f444cac3d072f5bd4be6386de397c27dfed3cfb603fb2863181100eb3b1253c0"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "da266cbb939a68c38dfc5e897d50a24e3b6998d24525fa60abe95db9527c6422"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_linux_amd64.tar.gz"
    end
  end

  name "changelog"
  desc "Keep a changelog without merge conflicts, one entry file per change"
  homepage "https://gitlab.com/l0nax/changelog-go"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "changelog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/changelog"]
    end
  end

  # No zap stanza required
end
