# This file was generated by GoReleaser. DO NOT EDIT.
cask "changelog" do
  version "2.0.0+1"

  on_macos do
    on_arm do
      sha256 "f51e3dae2f449b230ffb7f1bfdb99148dc38ff551f0d35b1380261a830bd53e7"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8eadf56e63e5ea492033b7332728656255326528ec974cfc006339922e0d0052"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "176d3c8a0c250f0b0f37cbbbbfb8393f129c41fa0313c9201aa419183efe5e7c"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3bc235cbb1785ff04476680b039c586c2afeeba3a1687420912ac60007683d65"
      url "https://gitlab.com/l0nax/changelog-go/-/releases/v#{version}/downloads/changelog_#{version}_linux_amd64.tar.gz"
    end
  end

  name "changelog"
  desc "Keep a changelog without merge conflicts, one entry file per change"
  homepage "https://gitlab.com/l0nax/changelog-go"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "changelog"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/changelog"]
    end
  end

  # No zap stanza required
end
