## this GoReleaser config is like the one which can be found in the project
## root, but this config does ONLY create the resulting binaries.
project_name: changelog

before:
  hooks:
    - go mod tidy

builds:
- id: "default"
  binary: changelog

  goos:
    - freebsd
    - linux
    - windows
    - darwin

  goarch:
    - amd64
    - arm
    - arm64

  ldflags:
    - -X gitlab.com/l0nax/changelog-go/pkg/version.Version={{.Env.VERSION}} -X gitlab.com/l0nax/changelog-go/pkg/version.Hash={{.Commit}} -X gitlab.com/l0nax/changelog-go/pkg/version.BuildTime={{.Env.BUILD_DATE}} -X gitlab.com/l0nax/changelog-go/pkg/version.Environment={{.Env.BUILD_ENVIRONMENT}}

## GitLab release
release:
  disable: true

changelog:
  skip: true
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
